# Build a Docker image with : Debian + JRE + python
# Uploading to docker-hub
# Workflow must be launched manually

name: Docker Image - Debian + JRE + Python

on:
  workflow_dispatch

env:
  IMAGE_NAME : "mercatus"
  VERSION : "v0.1"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
