# Build a Docker image with Dockerfile in root of repo
# Uploading to docker-hub

# This workflow must be launched manually

name: Docker Image

on:
  workflow_dispatch

env:
  IMAGE_NAME : "mercatus"
  VERSION : "v0.1"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
